/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.example.MotorPHPayrollUI;


import java.awt.HeadlessException;
import java.io.File;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.List;
import java.util.Scanner;
import javax.swing.JOptionPane;





import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rovie
 */
public final class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    
    int id;
    
    public MainFrame() {
        
        initComponents();
        loadEmployeesFromCSV();
        addRowToTable();
     
    }
    
    public int getId(){ return id;}
    public void setId(int id){ this.id = id; }
    
    
    private static final List<Employee> employees = new ArrayList<>();
    
    public static void loadEmployeesFromCSV() {
        File file = new File("employees.csv");
        if (!file.exists()) {
            return;
        }
        
        employees.clear();

        try (Scanner fileScanner = new Scanner(file)) {
            
            while (fileScanner.hasNextLine()) {
                String line = fileScanner.nextLine();
                String[] data = line.split(",");
                
                if (data.length < 11) {
                 System.out.println("Skipping invalid line: " + line);
                 continue;
                }

                int id = Integer.parseInt(data[0].trim());
                String firstname = data[1];
                String lastname = data[2];
                String birthday = data[3];
                String position = data[4];
                double rate = Double.parseDouble(data[5].trim());
                String status = data[6];
                String sssNum = data[7];
                String phNum = data[8];
                String tinNum = data[9];
                String piNum = data[10];

                employees.add(new Employee(id, firstname, lastname, birthday, 
                        position, rate, status, sssNum, phNum, tinNum, piNum));
            }
            
        } catch (Exception e) {
            
            System.out.println("Error reading CSV: " + e.getMessage());
        }
        
    }
 
    
    public void addRowToTable(){
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
         
        model.setRowCount(0);
        Collections.sort(employees, Comparator.comparingInt(Employee::getId));

         Object[] rowData = new Object[7];
         
        
         try{
        for (Employee e : employees) {
            
                rowData[0] = e.getId();
                rowData[1] = e.getLastname();
                rowData[2] = e.getFirstname();
                rowData[3] = e.getSssNum();
                rowData[4] = e.getPhNum();
                rowData[5] = e.getTinNum();
                rowData[6] = e.getPiNum();
                
                model.addRow(rowData);
                
            }
            
         
            }
            catch(HeadlessException e){
            }   
    }
    
    public void refreshTable() {
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    model.setRowCount(0); // Clear existing rows

    for (Employee e : employees) {
        model.addRow(new Object[]{
            e.getId(), e.getLastname(), e.getFirstname(),
            e.getSssNum(), e.getPhNum(), e.getTinNum(), e.getPiNum()
                
        });
    }
}
    
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        viewEmployeeBtn = new javax.swing.JButton();
        addEmployeeBtn = new javax.swing.JButton();
        editEmployeeBtn = new javax.swing.JButton();
        deleteEmployeeBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MainFrame");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Employee No.", "Last Name", "First Name", "SSS No.", "Philhealth No.", "Tin No.", "Pag-Ibig No."
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);

        viewEmployeeBtn.setText("View Employee Detail");
        viewEmployeeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewEmployeeBtnActionPerformed(evt);
            }
        });

        addEmployeeBtn.setText("Add New Employee");
        addEmployeeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEmployeeBtnActionPerformed(evt);
            }
        });

        editEmployeeBtn.setText("Edit Employee");
        editEmployeeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editEmployeeBtnActionPerformed(evt);
            }
        });

        deleteEmployeeBtn.setText("Delete Employee");
        deleteEmployeeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteEmployeeBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 888, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(viewEmployeeBtn)
                .addGap(18, 18, 18)
                .addComponent(addEmployeeBtn)
                .addGap(18, 18, 18)
                .addComponent(editEmployeeBtn)
                .addGap(18, 18, 18)
                .addComponent(deleteEmployeeBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewEmployeeBtn)
                    .addComponent(addEmployeeBtn)
                    .addComponent(editEmployeeBtn)
                    .addComponent(deleteEmployeeBtn))
                .addContainerGap(71, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void viewEmployeeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewEmployeeBtnActionPerformed
        
        
        if(jTable1.getSelectedRow() != -1){
            
            id =  (int) jTable1.getValueAt(jTable1.getSelectedRow(), 0);
            
            EmployeeDetails employeeDetails = new EmployeeDetails(id);
            this.setId(id);
            employeeDetails.setVisible(true);
            this.setVisible(false);
            
        }
        else {
            JOptionPane.showMessageDialog(this, "Please select an employee.");
        }   
    }//GEN-LAST:event_viewEmployeeBtnActionPerformed

    private void addEmployeeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEmployeeBtnActionPerformed
        
        
       AddNewEmployee addEmployee = new AddNewEmployee();
       addEmployee.setVisible(true);
       this.setVisible(false);
        
    }//GEN-LAST:event_addEmployeeBtnActionPerformed

    private void editEmployeeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editEmployeeBtnActionPerformed
   
        
         if(jTable1.getSelectedRow() != -1){
             id = (int) jTable1.getValueAt(jTable1.getSelectedRow(), 0);
             EditEmployee editEmployee = new EditEmployee(this, id);
             editEmployee.setVisible(true);
             this.setVisible(false);
        }
        else {
            JOptionPane.showMessageDialog(this, "Please select an employee.");
        }   
    }//GEN-LAST:event_editEmployeeBtnActionPerformed

    private void deleteEmployeeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteEmployeeBtnActionPerformed
       
        if(jTable1.getSelectedRow() != -1){
             id = (int) jTable1.getValueAt(jTable1.getSelectedRow(), 0);
             Employee employee = new Employee();
             employee.deleteEmployee(id);
             String message = "Employee Info Has Been Deleted!";
             JOptionPane.showMessageDialog(this, message);
             this.dispose();
             this.refreshTable();
             this.setVisible(true);
             
        }
        else {
            JOptionPane.showMessageDialog(this, "Please select an employee.");
        }   
        
    }//GEN-LAST:event_deleteEmployeeBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
    
      
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MainFrame().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addEmployeeBtn;
    private javax.swing.JButton deleteEmployeeBtn;
    private javax.swing.JButton editEmployeeBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton viewEmployeeBtn;
    // End of variables declaration//GEN-END:variables
}
